# Generated by Django 4.0.1 on 2022-02-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('heading_one', models.CharField(max_length=500)),
                ('content_one', models.CharField(max_length=7500)),
                ('heading_two', models.CharField(max_length=500)),
                ('content_two', models.CharField(max_length=7500)),
                ('heading_three', models.CharField(max_length=500)),
                ('content_three', models.CharField(max_length=7500)),
                ('publish_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
