# Generated by Django 4.0.1 on 2022-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Desctription', models.CharField(max_length=300)),
                ('Pub_Date', models.DateField()),
            ],
        ),
    ]
